// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: chitty_chat/chitty_chat.proto

package chitty_chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chitty_chat_chitty_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chitty_chat_chitty_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_chitty_chat_chitty_chat_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MessageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MessageReply) Reset() {
	*x = MessageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chitty_chat_chitty_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReply) ProtoMessage() {}

func (x *MessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_chitty_chat_chitty_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReply.ProtoReflect.Descriptor instead.
func (*MessageReply) Descriptor() ([]byte, []int) {
	return file_chitty_chat_chitty_chat_proto_rawDescGZIP(), []int{1}
}

func (x *MessageReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_chitty_chat_chitty_chat_proto protoreflect.FileDescriptor

var file_chitty_chat_chitty_chat_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x68, 0x69, 0x74, 0x74, 0x79, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x63, 0x68,
	0x69, 0x74, 0x74, 0x79, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x63, 0x68, 0x69, 0x74, 0x74, 0x79, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x22, 0x22, 0x0a, 0x0e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x20, 0x0a, 0x0c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x32, 0x52, 0x0a, 0x0a, 0x43, 0x68, 0x69, 0x74, 0x74, 0x79, 0x43, 0x68, 0x61, 0x74,
	0x12, 0x44, 0x0a, 0x0a, 0x67, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b,
	0x2e, 0x63, 0x68, 0x69, 0x74, 0x74, 0x79, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x68,
	0x69, 0x74, 0x74, 0x79, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x6c, 0x61, 0x73, 0x62, 0x75, 0x65, 0x2f, 0x41, 0x33,
	0x2d, 0x44, 0x53, 0x2f, 0x63, 0x68, 0x69, 0x74, 0x74, 0x79, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chitty_chat_chitty_chat_proto_rawDescOnce sync.Once
	file_chitty_chat_chitty_chat_proto_rawDescData = file_chitty_chat_chitty_chat_proto_rawDesc
)

func file_chitty_chat_chitty_chat_proto_rawDescGZIP() []byte {
	file_chitty_chat_chitty_chat_proto_rawDescOnce.Do(func() {
		file_chitty_chat_chitty_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_chitty_chat_chitty_chat_proto_rawDescData)
	})
	return file_chitty_chat_chitty_chat_proto_rawDescData
}

var file_chitty_chat_chitty_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chitty_chat_chitty_chat_proto_goTypes = []interface{}{
	(*MessageRequest)(nil), // 0: chitty_chat.MessageRequest
	(*MessageReply)(nil),   // 1: chitty_chat.MessageReply
}
var file_chitty_chat_chitty_chat_proto_depIdxs = []int32{
	0, // 0: chitty_chat.ChittyChat.getMessage:input_type -> chitty_chat.MessageRequest
	1, // 1: chitty_chat.ChittyChat.getMessage:output_type -> chitty_chat.MessageReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chitty_chat_chitty_chat_proto_init() }
func file_chitty_chat_chitty_chat_proto_init() {
	if File_chitty_chat_chitty_chat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chitty_chat_chitty_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chitty_chat_chitty_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chitty_chat_chitty_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chitty_chat_chitty_chat_proto_goTypes,
		DependencyIndexes: file_chitty_chat_chitty_chat_proto_depIdxs,
		MessageInfos:      file_chitty_chat_chitty_chat_proto_msgTypes,
	}.Build()
	File_chitty_chat_chitty_chat_proto = out.File
	file_chitty_chat_chitty_chat_proto_rawDesc = nil
	file_chitty_chat_chitty_chat_proto_goTypes = nil
	file_chitty_chat_chitty_chat_proto_depIdxs = nil
}
